dependencies:
  - name: mq-infra
    version: 0.0.1
    repository: https://artifactory-tools.itzroks-270007bykv-omcmf3-4b4a324f027aea19c5cbc0c3275c4656-0000.sjc03.containers.appdomain.cloud/artifactory/generic-local/ci
