apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBoVPK6iLYbJRUa2OJ6gDnkbNBZ2I7AHxNj+OvRe4e5hHh5pqyRX3Qaugefdf6pTaJ2wOEwQL/EvpYEFpcUxEGzQmLlVwr+yzvLR1WWUXg1dYpwHo8Y/mWrYjp1nLFCNO0bUN7bK8zd+LxHvhFHC0ru3+07b3vXeueZNZODDduPAVURdzJjCoxaaEFZpUPrMxSVof0mmfTt5lMwQHUTtc4ilSwYc+vL3fGAuSxmQURlg4/fFvwz4jVsemTPceyBlvlPmiocEMV1VP6xZAhRc1HArkDCJ+b06Qd1ca8++yTmxKlFem8RQB6nxQCFo4odHuuTPRcJOYc8G+XBSg62WV7kNFqVcs+/G6i7sx4e/cf6ODyHAdWZqSa5xw1M0kz9lQw5JV4Vb6InRT6n0HPeKEmKXrl+1YJ9LWr1D6eH7vrjlptARIWcNmgti1afnkhpwQK2DEKYvlpLDT/Tx8bOX5+VMcD8qLQO/iKde3RBp+zidSGfpgvfUk3X5D3DkKGPw2zwnvOBOyT980NMIMeOxImsiD1SNqllNgOlqvrQt9KJxMgF9qWqjvK2ucblinNOmLNSdrRMdU6pFJJDfcbwWZ+/xaPZy/fddGdlvDs//YMOal5xVsDhEWNuZkKkffy0S11fKFSrsQyRdbKHkKmwr82EQk5yVdK8TMsyT4YGFyKKaQ0e4WFDXAnNken1PbSyTP0WYdJPWkTE3Xxd/XinXZ/DgDWOFS49QF83V5Y0EPwkqmrNDauBYWPUlJeZuO3sxXCxV51ydfV+j5xSaCnUBwkLvV17p+e0x3OP2oDa4o6Y2GoRVqDaHCp5EtJvWHXPyed631LQUdA0pbC20NewIFzInBmxaEgnj9Q0spFQYSo0K7uqNDhc7Dw1mELJBeqR9lyfmGAHBjoQy2HrtrMNmc5ja2HXOW1JRcT6QTCRc/6FuA==
    IBM_ENTITLED_REGISTRY_USER: AgCIRaAQQm4VnTWKIVkca6RAJJuRj5DD7yXBSQEDausNfPPwglMy1cMmgrKjQmRoZvSwKwqfmem8BxYnjj98GTZuMh+bNZ0YOfKYHoVBa6CpqP3c8wgNIkgeQv1NEElhWCYecSeGZAjqmxQgeyUiy1Vo7Lcyeb/m1sNgVuY++QVydzaVvIzyPkzaBmivI2JEXfDin28PBk8WuHS9ecmixHtvEPo91z+1MOUl3EsQI1jlpzMHa8RsKjKQVkqj6mqopRM/SWLvsd+31L5hgMH97Ivt7+oi6Zk8QN5iCMjhRHxjsC0GZB9fD0jYBFPZpAb4NeI70cc6JNzC2yqCKt7NUl0fjAevLni5wk94oQQ1CscJHDEfUGSyhZ1E9PZPzWEDKRZLFo9dtHbBnldIVPkU2i6RNn/wfscfmx7A0ZUmpocQnIXBTjnPIVOm91brRQdb4OC67uFkm9TQCgOV6NB2tk3N2KHKd+QOrGgj+MPVZek2PahvxnNbzxku25es/P4vMPYaAwVu1EVwERipCy24s7p09UqqH/kPPiXVkWKUIGFDGq3p+4t/EuzJxJag8Y2po/XVVwi/7gxDvgrQ54yxnStt65ya9n16BaIShq9GnRVpFLhFR3JR2xOM2oDiTKAcDHOBWCQOpj1wA5fjoWwNGUSFHxwu52c5/cl9WQF9sUjinBy7YoXbYfgh6M8giAZcP6kBSg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

